# Generated by Django 6.0.4 on 2026-04-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('finalizado', 'Finalizado')], default='en_curso', max_length=15)),
                ('ronda_actual', models.IntegerField(default=1)),
                ('cuadro', models.JSONField(default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.IntegerField()),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[('victoria', 'Victoria'), ('derrota', 'Derrota'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('eventos', models.JSONField(default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='partidos.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goleadores', models.JSONField(default=dict)),
                ('porteros', models.JSONField(default=dict)),
                ('regates', models.JSONField(default=dict)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('goles_marcados', models.IntegerField(default=0)),
                ('goles_recibidos', models.IntegerField(default=0)),
                ('ronda_alcanzada', models.IntegerField(default=0)),
                ('campeon', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_torneos', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='partidos.torneo')),
            ],
        ),
    ]
