# Generated by Django 6.0.4 on 2026-04-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticastorneo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_torneos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torneo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='partidos.torneo'),
        ),
        migrations.AddField(
            model_name='estadisticastorneo',
            name='torneo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='partidos.torneo'),
        ),
    ]
