# Generated by Django 6.0.4 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('shot', 'Tiro'), ('save', 'Parada'), ('dribble', 'Regate'), ('defense', 'Bloqueo'), ('defense', 'Quitar'), ('combo', 'Combo')], max_length=20)),
                ('subtipo', models.JSONField(default=list)),
                ('elemento', models.CharField(blank=True, choices=[('Fuego', 'Fuego'), ('Montana', 'Montaña'), ('Aire', 'Aire'), ('Bosque', 'Bosque')], max_length=20)),
                ('imagen_elemento', models.CharField(blank=True, max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255)),
                ('poder_base', models.IntegerField(default=0)),
                ('coste_stamina', models.IntegerField(default=0)),
                ('coste_tension', models.IntegerField(default=0)),
                ('copias', models.ManyToManyField(blank=True, related_name='tecnicas_copiadas', to='personajes.personaje')),
                ('creadores', models.ManyToManyField(blank=True, related_name='tecnicas_creadas', to='personajes.personaje')),
                ('herederos', models.ManyToManyField(blank=True, related_name='tecnicas_heredadas', to='personajes.personaje')),
            ],
        ),
    ]
