# Generated by Django 6.0.4 on 2026-04-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnica',
            name='elemento',
            field=models.CharField(blank=True, choices=[('Fuego', 'Fuego'), ('Montaña', 'Montaña'), ('Aire', 'Aire'), ('Bosque', 'Bosque')], max_length=20),
        ),
    ]
