# Generated by Django 6.0.4 on 2026-04-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='equipos_guardados',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
