# Generated by Django 6.0.4 on 2026-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('academia', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=20)),
                ('color_principal', models.CharField(blank=True, max_length=7)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('entrenador_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('temporadas', models.JSONField(default=list)),
                ('jugadores', models.ManyToManyField(blank=True, related_name='equipos', to='personajes.personaje')),
            ],
        ),
    ]
