# Generated by Django 6.0.4 on 2026-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('posicion', models.CharField(choices=[('GK', 'Portero'), ('DF', 'Defensa'), ('MD', 'Centrocampista'), ('FW', 'Delantero')], max_length=5)),
                ('elemento', models.CharField(choices=[('Fuego', 'Fuego'), ('Montaña', 'Montaña'), ('Aire', 'Aire'), ('Bosque', 'Bosque')], max_length=20)),
                ('naturaleza', models.CharField(blank=True, choices=[('Justicia', 'Justicia'), ('Tension', 'Tensión'), ('Contraataque', 'Contraataque'), ('Afinidad', 'Afinidad'), ('Brecha', 'Brecha'), ('Juego Sucio', 'Juego Sucio')], max_length=20)),
                ('tier', models.CharField(blank=True, choices=[('S+', 'S+'), ('S', 'S'), ('A', 'A'), ('B', 'B')], max_length=2)),
                ('es_capitan', models.BooleanField(default=False)),
                ('grupo_edad', models.CharField(blank=True, max_length=50)),
                ('curso', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('imagen', models.CharField(blank=True, max_length=255)),
                ('imagen_detalle', models.CharField(blank=True, max_length=255)),
                ('imagen_posicion', models.CharField(blank=True, max_length=255)),
                ('imagen_elemento', models.CharField(blank=True, max_length=255)),
                ('imagen_pais', models.CharField(blank=True, max_length=255)),
                ('poder', models.IntegerField(default=0)),
                ('control', models.IntegerField(default=0)),
                ('tecnica', models.IntegerField(default=0)),
                ('presion', models.IntegerField(default=0)),
                ('fisico', models.IntegerField(default=0)),
                ('agilidad', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('remate', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('disputa', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=100)),
                ('tension', models.IntegerField(default=100)),
            ],
        ),
    ]
