# Generated by Django 6.0.4 on 2026-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_japones', models.CharField(blank=True, max_length=100)),
                ('elemento', models.CharField(choices=[('Fuego', 'Fuego'), ('Montana', 'Montaña'), ('Aire', 'Aire'), ('Bosque', 'Bosque')], max_length=20)),
                ('posicion', models.CharField(choices=[('Delantero', 'Delantero'), ('Centrocampista', 'Centrocampista'), ('Defensa', 'Defensa'), ('Portero', 'Portero')], max_length=20)),
                ('equipo', models.CharField(blank=True, max_length=100)),
                ('poder', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True)),
                ('tiro', models.IntegerField(default=0)),
                ('cuerpo', models.IntegerField(default=0)),
                ('control', models.IntegerField(default=0)),
                ('parada', models.IntegerField(default=0)),
                ('velocidad', models.IntegerField(default=0)),
                ('resistencia', models.IntegerField(default=0)),
                ('agallas', models.IntegerField(default=0)),
                ('libertad', models.IntegerField(default=0)),
            ],
        ),
    ]
