# Generated by Django 6.0.4 on 2026-04-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='agallas',
            new_name='agilidad',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='cuerpo',
            new_name='defensa',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='libertad',
            new_name='disputa',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='parada',
            new_name='fisico',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='resistencia',
            new_name='inteligencia',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='tiro',
            new_name='presion',
        ),
        migrations.RenameField(
            model_name='personaje',
            old_name='velocidad',
            new_name='remate',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='personaje',
            name='nombre_japones',
        ),
        migrations.AddField(
            model_name='personaje',
            name='curso',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personaje',
            name='es_capitan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaje',
            name='grupo_edad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen_detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen_elemento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen_pais',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaje',
            name='imagen_posicion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personaje',
            name='naturaleza',
            field=models.CharField(blank=True, choices=[('Justicia', 'Justicia'), ('Tension', 'Tensión'), ('Contraataque', 'Contraataque'), ('Afinidad', 'Afinidad'), ('Brecha', 'Brecha'), ('Juego Sucio', 'Juego Sucio')], max_length=20),
        ),
        migrations.AddField(
            model_name='personaje',
            name='pais',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='personaje',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='personaje',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaje',
            name='stamina',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='personaje',
            name='tecnica',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaje',
            name='tension',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='personaje',
            name='tier',
            field=models.CharField(blank=True, choices=[('S+', 'S+'), ('S', 'S'), ('A', 'A'), ('B', 'B')], max_length=2),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='posicion',
            field=models.CharField(choices=[('GK', 'Portero'), ('DF', 'Defensa'), ('MD', 'Centrocampista'), ('FW', 'Delantero')], max_length=5),
        ),
    ]
