# Generated by Django 6.0.4 on 2026-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0002_rename_agallas_personaje_agilidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='elemento',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Montaña', 'Montaña'), ('Aire', 'Aire'), ('Bosque', 'Bosque')], max_length=20),
        ),
    ]
